### ISSUE TITLE
Average rating for the field type

### ISSUE THREAD

**Issue by carlcs** [doublesecretagency/craft-starratings#1]
The field type isn’t always added to the element which is rated directly, so it would be nice if the field type had a “rate target” setting that’s a mini Twig template like a section’s Entry URI format, so you can compose a string like `product-27` when it’s saved.

With this you’d be able to calculate averages for every “rate target”.

**Comment by carlcs** [comment]
Duh… it’s a duplicate of #2

**Comment by lindseydiloreto** [comment]
Thanks @carlcs! Looks like we posted at (roughly) the same time. 🍺
