### ISSUE TITLE
FR: Add ability to load CSS & JS on demand

### ISSUE THREAD

**Issue by johndwells** [doublesecretagency/craft-starratings#13]
I'm using Star Ratings on a project that is SPA-esque, in that the CSS & JS is loaded only once, and then subsequent navigating is all marshaled via AJAX. I have found that the CSS & JS which Star Ratings needs to do its magic is only output if necessary (e.g. if a star rating is to be displayed on a page, then the asset bundle is registered on the view). But star ratings aren't everywhere on this project, for example not on the homepage.

It would be great if I could register the asset bundles on any request. Something as simple as:

```
{% do craft.starRatings.includeJs() %}
{% do craft.starRatings.includeCss() %}
```

**Comment by lindseydiloreto** [comment]
Hey @johndwells, sorry for the late response to this! I just realized that it's a lot easier than I thought it was, and it's already possible without me making any additional changes.

You may already be using [this code](https://plugins.doublesecretagency.com/star-ratings/disable-js-or-css/) to prevent the JS and/or CSS from being loaded automatically...

```twig
{% do craft.starRatings.disable(['css','js']) %}
```

But if you want to **manually** load those exact same files, it would look like this...

```twig
{% do view.registerAssetBundle("doublesecretagency\\starratings\\web\\assets\\JsAssets") %}
{% do view.registerAssetBundle("doublesecretagency\\starratings\\web\\assets\\CssAssets") %}
{% do view.registerAssetBundle("doublesecretagency\\starratings\\web\\assets\\FontAwesomeAssets") %}
```

That's it! Feel free to apply whichever of those files are necessary for your particular site... you may choose to disregard FontAwesome or the CSS entirely.

And just so no one else gets stuck in the same way, I went ahead and added a [new page](https://plugins.doublesecretagency.com/star-ratings/manually-load-js-or-css-assets/) to the docs.

Hope that helps! 🙂

**Comment by johndwells** [comment]
@lindseydiloreto Ah of course! I always forget about the ability to register bundles via twig.

However, it doesn't look like including the JsAssets bundle is _quite_ enough...

The `StarRatingsVariable::_includeJs()` method does more than just register the JS bundle. It also writes some JS inline, to do things like customize the star icons, add a CSRF token name & value to the `window` object, and a couple of other settings.

Now with your hint about the bundle registering, I can in fact do everything that `_includeJs()` does:

```
{% set starIcons = {
  '0/4': svg.use('star', 'fill-current w-1em h-1em'),
  '1/4': svg.use('star', 'fill-current w-1em h-1em'),
  '2/4': svg.use('star', 'fill-current w-1em h-1em'),
  '3/4': svg.use('star', 'fill-current w-1em h-1em'),
  '4/4': svg.use('star', 'fill-current w-1em h-1em'),
} %}
{% do craft.starRatings.disable(['js', 'css']) %}
{% do view.registerAssetBundle("doublesecretagency\\starratings\\web\\assets\\JsAssets") %}
{% do craft.starRatings.setIcons(starIcons) %}
{% js %}
  {% for k, v in starIcons %}
    starRatings.starIcons["{{ k }}"] = {{ v|json_encode|raw }};
  {% endfor %}
  starRatings.ratingChangeAllowed ={{ craft.app.getPlugins().getPlugin('star-ratings').getSettings().allowRatingChange ? 'true' : 'false' }};
  starRatings.devMode = {{ devMode ? 'true' : 'false' }};
  window.csrfTokenName = {{ craft.app.config.general.csrfTokenName|json_encode|raw }};
  window.csrfTokenValue = {{ craft.app.request.csrfToken|json_encode|raw }};
{% endjs %}
```

So this gets me back in business; but it's slightly brittle in that if anything ever changes in `_includeJs()` I might need to make adjustments to stay in sync. I still think it might be worth simply making `_includeJs()` a publicly available, in which case I could replace half of that with a simple:

```
{% do craft.starRatings.includeJs() %}
```

Thanks for your help!
