### ISSUE TITLE
Permissions error when submitting as non-logged in user

### ISSUE THREAD

**Issue by AdamChlan** [doublesecretagency/craft-starratings#14]
I am allowing non-logged in users rate entries, but when I submit the form, I get a 403 forbidden error, although the rating does get recorded successfully. Is there something special that needs to happen to keep the permission message from showing? The main Craft installation allows user registration, just in case that is needed. I'm also using the craft Guest Entry plugin on the site, so not sure if there is some sort of conflict there. Thanks.

**Comment by lindseydiloreto** [comment]
Hi @AdamChlan,

Sounds a bit complex. I probably have a ton of follow-up questions, and would maybe like to see some code snippets.

Would you mind pinging me on Craft Discord? We can troubleshoot the issue together in real-time.

Thanks!

**Comment by AdamChlan** [comment]
Sounds good, I'll try to reach out today. Thank you!
