### ISSUE TITLE
Call for User identity causes error

### ISSUE THREAD

**Issue by clarknelson** [doublesecretagency/craft-starratings#19]
I am trying to call `Craft::$app->getUser()->getIdentity()` within my module code but I believe there is an error being thrown in your plugin.

![Screenshot from 2022-01-03 08-24-16](https://user-images.githubusercontent.com/4106671/147948886-36246e75-05a6-4d97-bc35-41f2b22926c6.png)

**Comment by lindseydiloreto** [comment]
Hi @clarknelson, sorry about that. I think you're running into the same bug noted [here...](https://github.com/doublesecretagency/craft-starratings/issues/18#issuecomment-978142210)

I'll try to get a patch out for it this week. In the meantime, feel free to roll back to v2.2.0 to avoid the problem for now.

**Comment by clarknelson** [comment]
No rush I found a way around this. You may want to resolve for others though.

Thanks

**Comment by lindseydiloreto** [comment]
This is fixed in **v2.2.2**. 👍 

Thanks for reporting!
