### ISSUE TITLE
Cannot Add New Entry with Average Rating Filed

### ISSUE THREAD

**Issue by theurbanu** [doublesecretagency/craft-starratings#29]
I cannot add a new entry while having the Average rating Field assigned to the section. I'm testing things, and the only fields I have in place for the section are the title and "average rating field," however, I'm unable to add a new entry. When I click the "add entry" button, nothing happens. This is only happening with this section and nothing else. When I disable the plugin or remove the field, I can add a new entry like normal. 

This is happening with Craft v 4.4.15

**Comment by JamesNock** [comment]
I've just pushed a PR for this https://github.com/doublesecretagency/craft-starratings/pull/30 hopefully it will get merged soon but if you want to fix it then there's the code to do it.

**Comment by lindseydiloreto** [comment]
This fix has been officially released in [v2.3.3](https://github.com/doublesecretagency/craft-starratings/releases/tag/2.3.3).

Thanks for submitting that patch @JamesNock! 🙏
