### ISSUE TITLE
Robots

### ISSUE THREAD

**Issue by smockensturm** [doublesecretagency/craft-starratings#4]
Hello,

Craft CMS 2.7.2
Star Ratings 1.3.0

What are the possibilities that bots or security scans or otherwise are 'clicking' on these star ratings and distorting the results? We have some weird data.

```
avgRating	totalVotes
3.723			18
2.896			19
4.821			11
5.003			3
5.003			3
1.346			52
5.002			4
-9.024			42       <<<<<
0.547			33
0.548			128      <<<<<
5.002			4
0.861			43
```

Not that 128 votes resulting in half a star is all that unusual, but I think it's an anomaly. And what's up with the negative rating?

Thanks for your help.

**Comment by lindseydiloreto** [comment]
Are you allowing anonymous ratings? If so, then yes it's possible for bots to cast bogus ratings.

From the settings page...
>"To prevent any chance of voting fraud, it's **highly recommended** that your users be logged in to rate. However, sometimes it's necessary to allow anonymous rating."

As for the negative number, I have no idea. The only thing I can imagine is that perhaps you changed the "Maximum Possible Rating" value at some point, after you already had existing ratings in the database.

**Comment by smockensturm** [comment]
Yes, we are allowing anonymous ratings. "Sometimes it's necessary."

Then of course our client asks, "Well, how do other sites that have ratings do it?"

¯\_(ツ)_/¯

Seems way weird to put an "I'm not a robot" captcha on ratings. Aaaaanyway... thanks!

**Comment by lindseydiloreto** [comment]
Yeah, I guess a CAPTCHA may be some sort of option. Will consider that for a future version.
