### ISSUE TITLE
Impossible to invoke a method ("stars") on a string variable ("5").

### ISSUE THREAD

**Issue by Chalkin** [doublesecretagency/craft-starratings#9]
When I try to display the rating on CraftCMS 3 (Twig Template) I always get:
`Impossible to invoke a method ("stars") on a string variable ("5").`
Version: "version": "2.1.1",

My template Code:
`{{ entry.recipeRating.stars(entry.id) }}`

**Comment by lindseydiloreto** [comment]
Looks like you're mixing up the different ways to output stars. There are actually two different ways to handle stars (depending on the needs of your project).

If you're handling stars [the default way](https://www.doublesecretagency.com/plugins/star-ratings/docs/display-star-ratings), it should look something like this...

```twig
{{ craft.starRatings.stars(entry.id) }}
```

If you're handling stars [as a field type](https://www.doublesecretagency.com/plugins/star-ratings/docs/rate-field-type), it should look something like this...

```twig
{{ craft.starRatings.lockedStars(entry.recipeRating) }}
```

Hope that helps!

**Comment by Chalkin** [comment]
Yes, that helped. Thank you
